### ISSUE TITLE
Unable to load video!

### ISSUE THREAD

**Issue by antbertrand** [anucvml/vidat#115]
Hello, well first I'd like to say that I was impressed with the demo, your tool is really simple, easy to use, and very powerful at the same time.
However, I've got some issues when trying to use it locally on my machine. I did start an ngnix web server on the website in the /src folder. I can access it, however i'm unable to import any local videos. It fails and returns it was unable to load the video !
I must say I'm not too familiar with all those steps, If you could maybe clarify a little bit the installation procedure.

One other question I have, is how the python code is involved. I can't find any way to use it.

Thanks for your help !

**Comment by DavidZhang73** [comment]
Thanks for your comment.

> I can access it, however i'm unable to import any local videos. It fails and returns it was unable to load the video!

What is the type of video? Have you tried different types? Like mp4 or webm? The issue is that the video types are limited by the browser itself. Also, change the browser maybe helpful (IE -> Chrome). And If it is possible, send the video to me, I can then debug with it.

> One other question I have, is how the python code is involved. I can't find any way to use it.

Python is used to deal with the final result file (annotation.json), which is saved to local computer after annotation. One can use that script to get annotation information or convert the file to preferred format. And of course, you can just read from the raw json file, then that python script is useless.

**Comment by sgould** [comment]
Further to @DavidZhang73's answer, are you able to load the same videos using one of the host installations, [host1](http://users.cecs.anu.edu.au/~sgould/vidat/) or [host 2](https://vidat.davidz.cn/)? If so, then the problem may be with your web server's security permissions.

**Comment by antbertrand** [comment]
Thank you guys, the error came from my video file I was using to test. It was in mp4 format, but it seems it was corrupted in a way ( however vlc was still able to open it). I had another video in .avi format that I couldn't import either, but I guess this format may not be handled. 
It works great now, thanks !
