### ISSUE TITLE
Video frames loading slowly

### ISSUE THREAD

**Issue by antbertrand** [anucvml/vidat#126]
I noticed the frames are loaded quite slowly, therefore using the slider is not smooth at all and it can make the annotation quite difficult, even more on videos with high fps. 
I saw that you use cv2.VideoCapture to load the frames from the video. It would be a great addition to use a more efficient video loading library, such as [decord](https://github.com/dmlc/decord) or [PyAV](https://pyav.org/docs/develop/index.html).
Those two are actually python bindings for the famous **FFmpeg** and they are used a lot to speed up the trainings of video classification networks. 
![71223638-7199f300-2289-11ea-9e16-104038f94a55](https://user-images.githubusercontent.com/46795127/114436348-82305400-9bc5-11eb-8b36-8be4a8d03b44.png)

**Comment by sgould** [comment]
Thanks for the comment and efficient Python video libraries. We use OpenCV in the demo code for processing annotations on the backend, but the annotation tool is written in javascript and runs completely within the browser. We'll investigate options for speeding up the slider, and user experience on large and high framerate videos.

**Comment by DavidZhang73** [comment]
> We'll investigate options for speeding up the slider, and user experience on large and high framerate videos.

The main reasons are:

1. The code in `src/js/components/videoLoader.js` shows how we cache the frames. Fundamentally, we use `seeked` event to load the frame via canvas and then save it to memory. This is the best/common practice but slow. The raw speed can be validated via the first demo without Vue.js.
2. As we introduce Vue.js, we need to make the cached frames to be responsive variables(add getters and setters) and share with all components via Vuex, which further slows the whole program.  

Some solution to be explored:

1. It seems that a new tech called `WebAssembly` can be used to improve the performance of frames caching. It can run more native languages like c/cpp to speed up. Something like [ffmpeg.wasm](https://github.com/ffmpegwasm/ffmpeg.wasm).
2. Applying Vue.js and Vuex making developing faster, but also leads to performance flaws. Some best practices of Vuex are not followed due to the IDE cannot detect Vue.js from raw js files, we might need to focus on that first. But the improvement cannot be guaranteed.
3. Maybe initially, instead of having all frames cached, we can just put a video element beneath the canvas. It uses the raw functionality of browser to load, cache, and play video. But the drawbacks are, like common video sites, the slider will be laggy, especially moving backwards.

**Comment by antbertrand** [comment]
Oh ok, the backend in python is not used in the annotation tool. Everything is done in js in the browser.
But I think it would be worth thinking of a way to give a smoother experience. Today when I load a 10 seconds video in let's say 720p 3O fps and press play, the video stutters and the shown fps is inconsistent and close to 3 or 4 fps. 

From what I understand you already used a clever way using different queues to prioritize the frame caching. I wouldn't know how to improve this, but maybe the somewhat bad performances are inherent to showing the video by displaying each frames. 
Maybe we could think of a way where when you move the sliders it shows underneath (as on youtube's progress bar)  thumbnails that were loaded and put in cache when you open the video.
Another idea would be to keep the video in video format, and when you move the glider we can see the video in a corner of the screen, and only when you stop moving, the frames are requested, cached and displayed. 

Those are ideas that would help to search for behaviors in a video before annotating them. In my case I have maybe 100 hours of video, that I sliced in 5 min segments, but it is still hard to see quickly if there are interesting behaviors in a video as it stutters and you might miss some.

 Oh and one last question, today what is the loading spinner in the top right meaning ? Should it stop spinning after a while when all the frames are cached ?
 
 Thanks a lot for this tool, I would be happy to discuss it more if needed

**Comment by antbertrand** [comment]
Oh I didn't see your answer David. Thank you for the technical clarification, I see you already have thoughts and ideas on how to improve that.

**Comment by DavidZhang73** [comment]
> Oh and one last question, today what is the loading spinner in the top right meaning ? Should it stop spinning after a while when all the frames are cached ?

Thanks for your comment:smile:, and yes, it is the caching indicator which will disappear when all frames are cached.

**Comment by DavidZhang73** [comment]
@antbertrand https://github.com/anucvml/vidat/commit/1fab7ace29690b78b7904960aa88d73e9eeb517b should improve the play performance. Take a try and looking forward to your reply.

**Comment by DavidZhang73** [comment]
A possible solution for slow scrubbing through the video:

When caching, wrap around from the current frame which should be faster if the codec is seeking from the current position.
