### ISSUE TITLE
Vertical scroll bar gitter when scrubbing video with annotations

### ISSUE THREAD

**Issue by sgould** [anucvml/vidat#156]
When scrubbing through a video with annotations, if the window is scaled so that the controls just fit without annotations and needs scrolling with annotations, then as the video moves through a labelled frame the vertical scrollbar will momentarily appear creating a small amount of jitter in the location of the controls. This can be annoying for the annotator.

See for example : https://users.cecs.anu.edu.au/~sgould/vidat2/?annotation=annotation/example.json#/

**Comment by DavidZhang73** [comment]
I see. It is because the vertical scroll is hidden and does not occupy any room when there is enough space, and there needs more space, the vertical scroll is made visible and occupy room. This is the default behaviour controlled by the browser, and it is different on different browsers.

Two potential solutions:

1. make the vertical scroll visible all the time.
2. replace it with a custom vertical scroll and make that small enough and set it to be absolute position which does not occupy any room.

I personally prefer the second one. WIP.
