### ISSUE TITLE
Support of local storage?

### ISSUE THREAD

**Issue by chenzhutian** [anucvml/vidat#167]
Hi! Thanks for the great tool!
I am wondering whether the web annotation tool can support local storage?
Currently it seems that all my annotation will be lost after refreshing the page.

Thanks!

**Comment by DavidZhang73** [comment]
Hi, thanks for your comment. 
It is by design that annotations are **not** stored in LocalStorage, because we need to cache frames from video, those frames are too large to be stores in LocalStorage. 
It is very hard to store the annotations only, because after refresh, user needs to select the identical previous video to be aligned with stored annotations. 
So, the suggested procedure would be _open the video_, _annotate_, _store to local computer_, if the user needs review, _open the video again_, _load the downloaded annotation file_ and _modify_.
